remote_theme: coursweb/jk-theme
title: Divers
description: Sous-module pour cours-web.ch, couvrant des sujets variés.
lang: fr-FR
chapters:
 - title: Cours-web
   url: https://cours-web.ch/
 - title: HTML
   url: https://cours-web.ch/html/
 - title: CSS
   url: https://cours-web.ch/html/
 - title: JavaScript
   url: https://cours-web.ch/javascript/
 - title: WordPress
   url: https://cours-web.ch/wp/
 - title: Serveurs
   url: https://cours-web.ch/serveurs/
 - title: Divers
   url: https://cours-web.ch/divers/
   # Footer content
# Content is split in three columns.   
footer_col_1: <ul class="contact-list">
  <li>Un support de cours</li>  
  <li>Eracom, Lausanne</li>
  <li>2017-2022</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/coursweb/divers">Lien Github</a></li></ul>